DEFAULT_IMAGE_NAME = "docker.io/bitnami/git"
DEFAULT_IMAGE_TAG = "2.43.0"
DEFAULT_DISPLAY_NAME = "Git Clone"
DEFAULT_CONTAINER_NAME = "main"

DEFAULT_MEMORY_REQUEST = '80Mi'
DEFAULT_MEMORY_LIMIT = '100Mi'
DEFAULT_CPU_REQUEST = '100m'
DEFAULT_CPU_LIMIT = '200m'

STARTUP_COMMAND = "git"

OUTPUT_DIR = "/repository"

GIT_USERNAME_ENV = "GIT_USERNAME"
GIT_TOKEN_ENV = "GIT_TOKEN"
